#!/bin/sh
# Create a new article

if [ ! -d "./_posts" ]; then
  echo "Path _posts/ doesn't exist. fe-practise"
else
  cd ./_posts
  filename="`date "+%Y-%m-%d-"`fe-practise.md"
  title=`echo "fe-practise" | tr "-" " "`
  date=`date "+ %Y-%m-%d %H:%M:%S"`
  echo -e "---\ntitle: $title\ndate: $date +0800\ncategory:\ntags:\nexcerpt:\n---" > $filename
fi
